name: Checkout
  uses: actions/checkout@v3
  with:
    submodules: 'recursive'
    # Make sure the repository URL and branch name are correct
    repository: SUPDAWGIE/AutomationSample
    ref: main  # If your default branch is named "main"
